version: "3.9"

services:
  web:
    build: ./web
    container_name: telecom-web
    ports:
      - "8081:80"

  nginx:
    image: nginx:latest
    container_name: telecom-nginx
    ports:
      - "8090:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web

  dns:
    image: internetsystemsconsortium/bind9:9.18
    container_name: telecom-dns
    ports:
      - "5353:53/tcp"
      - "5353:53/udp"
    volumes:
      - ./dns/config:/etc/bind       # tous les named.conf*
      - ./dns/zones:/etc/bind/zone   # fichier de zone db.elite.dev.tn
    restart: unless-stopped
